### ISSUE TITLE
RFC: Create a plugin system for generating code

### ISSUE THREAD

**Issue by mattpocock** [mattpocock/sextant#10]
## Using plugins

You'd use plugins by adding a `sextant.config.js` inside the directory you target with `sextant ./target-dir`. The config file might look like this:

```js
// sextant.config.js

module.exports = {
  plugins: [
    // Reference to a node_module, with config
    ['@sextant-tools/plugin-typescript', { configOption: true }],

    // Reference to a local plugin file
    './local-plugin-file.js',

    // An inline implementation of a plugin
    createPlugin(() => {}),
  ]
}
```

> I'm also envisaging that users could add plugins and manage configuration through the Sextant GUI, giving an awesome experience for folks wanting to explore plugin possibilities.

## Creating a plugin

`@sextant-tools/core` would export a function: `createPlugin`. This could be used like this:

```js
// sextant-plugin.js
const { createPlugin } = require('@sextant-tools/core');

module.exports = createPlugin((sextantContext, pluginConfig) => {
  // do something with the data you get
})
```

I'm in favour of the `createPlugin` syntax because you get more discoverability of our API through Typescript inference on `sextantContext` and `pluginConfig`.

From here, you have access to the usual node API's, as well as any custom API's we'll give you to through `sextantContext`.

**Comment by ezhikov** [comment]
I have various questions with no particular order:

- There is nice pattern used by babel and eslint where you can omit insignificant part of name, like `env` instead of `babel-preset-env` and `airbnb` instead of `eslint-config-airbnb`. Will you consider adding such naming convention?
- Will it be possible to forward errors from plugins to interface? I believe there should be dedicated API for this.
- Will it be possible to modify interface itself to extend not only code generation, but also data generation in convenient way? Let's say, I'm modeling my API client. I'd like to specify methods, additional headers, etc. I believe it would be possible to determine this parameters from features or scenarios, but it will introduce contract that might lead to errors. Also there can be different types of parameters - some go to `path`, some to body or into get params.

**Comment by mattpocock** [comment]
> There is nice pattern used by babel and eslint where you can omit insignificant part of name, like env instead of babel-preset-env and airbnb instead of eslint-config-airbnb. Will you consider adding such naming convention?

Possibly - we'll go that way if required, but I don't feel good guaranteeing it from the start. Other plugin systems, like Gatsby, don't do this, and I think I prefer the explicit package names. It's more discoverable and easier to debug.

> Will it be possible to forward errors from plugins to interface? I believe there should be dedicated API for this

This is a nice idea - what would this mean? What kind of errors are you imagining?

Any plugin errors would also surface in the console.

> Will it be possible to modify interface itself to extend not only code generation, but also data generation in convenient way? Let's say, I'm modelling my API client. I'd like to specify methods, additional headers, etc. I believe it would be possible to determine this parameters from features or scenarios, but it will introduce contract that might lead to errors. Also there can be different types of parameters - some go to path, some to body or into get params.

Could you explain more about this? It sounds like you might need a custom plugin to match your needs, or for the plugin to generate code that could be extended in the right way.

**Comment by ditorojuan** [comment]
> Will it be possible to modify interface itself to extend not only code generation, but also data generation in convenient way? Let's say, I'm modelling my API client. I'd like to specify methods, additional headers, etc. I believe it would be possible to determine this parameters from features or scenarios, but it will introduce contract that might lead to errors. Also there can be different types of parameters - some go to path, some to body or into get params.

I really like this idea by @ezhikov, I think plugins will benefit a lot from custom windows(that runs on react) where they can declare extra fields and context on certain environments/actions even scenarios. For example: A plugin that handles some serverless provider(such as AWS) will like to know which environment belongs  to which service(lambda, ec2, eks, etc...) so it can generate the necessary boilerplate for the deployments

**Comment by ezhikov** [comment]
> Any plugin errors would also surface in the console.

As you said in #6 that you want it to be usable for non tech people and this will definitely exclude console users. As an example - there may be overlay, like overlay of webpack dev server, or there can be dedicated panel in interface (probably, collapsible) to show errors. Actually, it can be build via plugin if we would be able to modify interface.
![example of interface panel with errors](https://user-images.githubusercontent.com/4413493/97780462-e1f5ee00-1b95-11eb-92a1-1fd6b09ac76d.png)

> What kind of errors are you imagining?

Let's say there is a contract or naming convention or just simply error in plugin. If end user make a mistake it will result in error in data generation or code generation. As example there is `@xstate/inspect` that breaks when you try to use object with circular references as event (like native UIEvent from DOM).

And about interface. Good example will be Storybook where you can interact with various entities via addons. There is manager and stories and addons can extend manager (add panels, for example) and extend stories (data generation in this case). Since manager and story is in different iframes, they communicate via messages (so, it can be modelled in Sextant). When we toggle somethin in manager, it affects story. Or panel might just show us some info (like addon to check basic accessibility in story).

**Comment by mattpocock** [comment]
@ditorojuan @ezhikov I think the goal of any plugin system should be to expose as few internals as possible. This makes me err on the side of caution when it comes to one thing specifically: exposing API's which interact directly with the GUI.

@ditorojuan Let's take the example of wanting to add custom fields and detail to environments/services etc from inside the GUI. The idea being that some implementations (like deploying actors/environments to cloud services etc) need extra information (AWS region, lambda name etc) in order to do it.

One way to manage this would be to create a plugin which outputted which environments need to be created, and which environments need permission to communicate between them. Instead of adding attributes/information inside the GUI, the plugin would create a function where you'd input them inside your IDE.

This is superior to doing it in the GUI, because you can actually get type checking in your IDE. We could do this in a GUI plugin with form validation etc, but it's a lot of faff and maintenance for something that we _can_ do natively.

This goes to an answer I wanted to give to @ezhikov's point: I think the plugin system should be useful/usable by developers only. I love the idea that a PM could specify a flow in Sextant (with the help of a dev), which would then spawn type errors that the developer would fill in to implement the system.

I think for now I'm happy sourcing errors inside the console (beautiful, readable errors for developers, mind you). But I'm not sure if we should give plugin creators API's to change/modify the GUI.

I'm unsure on this, though - and am willing to be proven wrong if there's a compelling case for it. I just don't want to commit to a ton of plugin features we then need to deprecate in the future when we decide the maintenance isn't worth the hassle.

**Comment by ezhikov** [comment]
As a more frontend guy, I'm more interested in collaboration between myself, designers and backend devs regarding interface building. Use case I thought about is that I can spawn sextant on my machine, and share interface with colleagues, who will make editions to scenarios and I'll just make additions to code after (or it will be re-generated by plugin) and use it immediately in my interfaces. This still can be done without extending GUI, but having errors (at least some) proxied to it would be awesome.

I totally understand why you don't want to extend GUI, and, to be honest, I see it as a very challenging task to organize good support for GUI plugins, especially in a way me and @ditorojuan think about it.

Part of my requirements _can_ be satisfied from contract for naming convention for scenario, like `GET /api/v1/entity/{id} OK` or `POST /api/v1/entity BAD`.

While I was writing this, another thought came to my mind. Since core and frontend packages are separate, I believe it would be possible to write another GUI and use it with core package if there will be possibility to use core separately. It would be definitely a better solution in terms of support and customizability.

**Comment by mattpocock** [comment]
> Part of my requirements can be satisfied from contract for naming convention for scenario, like GET /api/v1/entity/{id} OK or POST /api/v1/entity BAD.

I think that adding custom fields for environments/services could be a _native_ part of Sextant. Then plugins could read from these custom fields, perhaps by specifying which one is relevant in a config file. But maybe we don't ever want to do things in Sextant that are better done in an IDE. Specifying POST or GET on API endpoints could be done either inside the plugin or in userland.

> While I was writing this, another thought came to my mind. Since core and frontend packages are separate, I believe it would be possible to write another GUI and use it with core package if there will be possibility to use core separately. It would be definitely a better solution in terms of support and customizability.

This is a cool idea. If we commit to a data structure in JSON there's no reason why someone couldn't read that JSON file and build whatever they wanted from it, even using utilities from `@sextant/core` to do so.

**Comment by ditorojuan** [comment]
I have been giving this more thought and I like this idea by @mattpocock  :
> This is a cool idea. If we commit to a data structure in JSON there's no reason why someone couldn't read that JSON file and build whatever they wanted from it, even using utilities from @sextant/core to do so.

Using `@sextant/core` more like an utility library we can enable developers to do any kind of crazy things with us not worrying about maintaining a complex structure between `@sextant/core` and `@sextant/frontend`. 

Also if they do their frontends and use `@sextant/core` as a backend for codegen will also(maybe) enable developers to jump-in into the pipeline for codegen to create all sort of things for their environments(perhaps they want to generate a custom react-hook which will let them just write the handler and not worry about react-specifics, just an example).
